plugin: rest

resources:
  - path: /api/users/{id}
    anyOf:
      - expression: "${context.request.headers.Authorization}"
        value: "Bearer admin-token"
        operator: "EqualTo"
      - expression: "${context.request.queryParams.apiKey}"
        value: "secret-key"
        operator: "EqualTo"
    response:
      template: true
      content: |
        {
          "id": "${context.request.pathParams.id}",
          "name": "John Doe",
          "role": "admin"
        }
      statusCode: 200
      headers:
        Content-Type: application/json

  - path: /api/orders
    allOf:
      - expression: "${context.request.headers.X-User-Role}"
        value: "admin"
        operator: "EqualTo"
      - expression: "${context.request.queryParams.region}"
        value: "EU"
        operator: "EqualTo"
    response:
      content: |
        {
          "orders": [
            {
              "id": "123",
              "status": "shipped"
            }
          ]
        }
      statusCode: 200
      headers:
        Content-Type: application/json
